const products = [
  { id: 1, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
  { id: 2, name: 'Áo Sơ Mi trắng', category: 'Áo thun', image: '/images/aomitrang.jpg', price: 2000 },
  { id: 3, name: 'Quần Jeans Xanh', category: 'Quần', image: '/images/quanjear1.jpg', price: 5000 },
  { id: 4, name: 'Áo Sơ Mi Đen', category: 'Áo thun', image: '/images/aosomiden2.jpg', price: 500 },
  { id: 5, name: 'Áo Sơ MI Xanh', category: 'Áo thun', image: '/images/aosomixanh.jpg', price: 400 },
  { id: 6, name: 'Mũ Đỏ', category: 'Mũ', image: '/images/mudo.jpg', price: 205 },
  { id: 7, name: 'Áo khoác gió màu đen', category: 'Áo khoác', image: '/images/aokhoac5.jpg', price: 680 },
  { id: 8, name: 'Giày màu tím', category: 'Giày', image: '/images/giaytim.jpg', price: 230 },
  { id: 9, name: 'Quần jean light Blue', category: 'Quần', image: '/images/quan1.jpg', price: 800 },
  { id: 10, name: 'Áo Khoác màu bạc', category: 'Áo khoác', image: '/images/aokhoac20.jpg', price: 330 },
  { id: 11, name: 'Áo khoác trắng', category: 'Áo khoác', image: '/images/aokhoac6.jpg', price: 700 },
  { id: 12, name: 'Áo Sơ mi bạc', category: 'Áo thun', image: '/images/ao somibac.jpg', price: 310 },
  { id: 13, name: 'Mũ Vàng', category: 'Mũ', image: '/images/muvang.jpg', price: 210 },
  { id: 14, name: 'Áo Khoác màu Nâu', category: 'Áo Khoác', image: '/images/aokhoac4.jpg', price: 680 },
  { id: 15, name: 'Áo thun tay ngắn', category: 'Áo thun', image: '/images/shirt.jpg', price: 250 },
  { id: 16, name: 'Giày Xanh', category: 'Giày', image: '/images/giayxanh.jpg', price: 270 },
  { id: 17, name: 'Áo Khoác gió màu đỏ', category: 'Áo khoác', image: '/images/aokhoac13.jpg', price: 430 },
  { id: 18, name: 'Áo thun đen', category: 'Áo thun', image: '/images/aothun4.jpg', price: 230 },
  { id: 19, name: 'Áo Sơ Mi', category: 'Áo thun', image: '/images/aoominagan.jpg', price: 540 },
  { id: 20, name: 'Áo Thun Xanh', category: 'Áo thun', image: '/images/aoxanh.jpg', price: 540 },
  { id: 21, name: 'Áo Khoác da màu nâu', category: 'Áo khoác', image: '/images/aokhoac14.jpg', price: 450 },
  { id: 22, name: 'Áo Khoác đen', category: 'Áo khoác', image: '/images/aokhoac9.jpg', price: 740 },
  { id: 23, name: 'Áo Khoác Gió Red', category: 'Áo khoác', image: '/images/aokhoac2.jpg', price: 500 },
  { id: 24, name: 'Quần Jeans Đen', category: 'Quần', image: '/images/quandn8.jpg', price: 700 },
  { id: 25, name: 'Áo khoác Xanh ', category: 'Áo khoác', image: '/images/aokhoac7.jpg', price: 750 },
  { id: 26, name: 'Áo Khoác G ió black', category: 'Áo khoác', image: '/images/aokhoac1.jpg', price: 500 },
  { id: 27, name: 'Giày trắng', category: 'Giày', image: '/images/giaytrang.jpg', price: 200 },
  { id: 28, name: 'Mũ Đen', category: 'Mũ', image: '/images/muden.jpg', price: 215 },
  { id: 29, name: 'Áo khoác màu đen', category: 'Áo khoác', image: '/images/aokhoac16.jpg', price: 410 },
  { id: 30, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
  { id: 31, name: 'Mũ Xanh', category: 'Mũ', image: '/images/muxanh.jpg', price: 225 },
  { id: 32, name: 'Giày thể thao', category: 'Giày', image: '/images/giaythethao.jpg', price: 230 },
  { id: 33, name: 'Áo Khoác màu nâu ', category: 'Áo khoác', image: '/images/aokhoac18.jpg', price: 340 },
  { id: 34, name: 'Áo Sơ MI ', category: 'Áo thun', image: '/images/aoomi1.jpg', price: 800 },
  { id: 35, name: 'Quần Jeans Xanh Bạc', category: 'Quần', image: '/images/quan1.jpg', price: 860 },
  { id: 36, name: 'Giày đen', category: 'Giày', image: '/images/giayden.jpg', price: 260 },
  { id: 37, name: 'Áo Thun trắng ', category: 'Áo thun', image: '/images/aothutrang4.jpg', price: 250 },
  { id: 38, name: 'Quần Jeans Đen', category: 'Quần', image: '/images/quan jean den4.jpg', price: 740 },
  { id: 39, name: 'Áo Khoác vàng', category: 'Áo khoác', image: '/images/aokhoac3.jpg', price: 660 },
  { id: 40, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
  { id: 41, name: 'Giày xanh', category: 'Giày', image: '/images/giay1.jpg', price: 210 },
  { id: 42, name: 'Áo Khoác màu hồng', category: 'Áo khoác', image: '/images/aokhoac11.jpg', price: 380 },
  { id: 43, name: 'Mũ Xanh Lá Cây', category: 'Mũ', image: '/images/muxanhlacay.jpg', price: 208 },
  { id: 44, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
  //giay thay anh ae
  { id: 45, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 46, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 47, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 48, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 49, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 50, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 51, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 52, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 53, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 54, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 55, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 56, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 57, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 58, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 59, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 60, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 61, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 62, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 63, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 64, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
  { id: 65, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 },
 //aokhoac thay anh ae
 { id: 66, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 67, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 68, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 69, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 70, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 71, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 72, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 73, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 74, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 75, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 76, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 77, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
 { id: 78, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
//aothun thay anh ae
{ id: 79, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 80, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 81, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 82, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 83, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 84, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 85, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 86, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 87, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 88, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 89, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 90, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 91, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 92, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 93, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
{ id: 94, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
//quan thay anh ae
{ id: 95, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 96, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 97, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 98, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 99, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 100, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 101, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 102, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 103, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 104, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 105, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 106, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 107, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 108, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 109, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 110, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 111, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 112, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 113, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 114, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
{ id: 115, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
//mu thay anh ae
{ id: 116, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 117, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 118, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 119, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 120, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 121, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 122, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 123, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 124, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 125, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 126, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 127, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 128, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 129, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 130, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 131, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 132, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 133, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 134, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 135, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
{ id: 136, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
];

const alternateImages = {
  'Giày': [
    '/images/giaytim.jpg',
    '/images/giayxanh.jpg',
    '/images/giaytrang.jpg',
    '/images/giaythethao.jpg',
    '/images/giayden.jpg',
    '/images/giay1.jpg',
    '/images/giaydentrang.jpg',
    '/images/shoes.jpg',
  ],
  'Áo khoác': [
    '/images/aokhoac1.jpg',
    '/images/aokhoac2.jpg',
    '/images/aokhoac3.jpg',
    '/images/aokhoac4.jpg',
    '/images/aokhoac5.jpg',
    '/images/aokhoac6.jpg',
    '/images/aokhoac7.jpg',
    '/images/aokhoac8.jpg',
    '/images/aokhoac9.jpg',
    '/images/aokhoac11.jpg',
    '/images/aokhoac13.jpg',
    '/images/aokhoac14.jpg',
    '/images/aokhoac16.jpg',
    '/images/aokhoac18.jpg',
    '/images/aokhoac20.jpg',
  ],
  'Áo thun': [
    '/images/aomitrang.jpg',
    '/images/aosomiden2.jpg',
    '/images/aosomixanh.jpg',
    '/images/ao somibac.jpg',
    '/images/shirt.jpg',
    '/images/aothun4.jpg',
    '/images/aoominagan.jpg',
    '/images/aoxanh.jpg',
    '/images/aoomi1.jpg',
    '/images/aosomivang.jpg',
    '/images/aothunnamchat.jpg',
    '/images/aothun polo.jpg',
    '/images/aothutrang4.jpg',
  ],
  'Quần': [
    '/images/quanjear1.jpg',
    '/images/quanjean2.jpg',
    '/images/quandn8.jpg',
    '/images/quan1.jpg',
    '/images/quan jean den.jpg',
    '/images/quan jean den3.jpg',
    '/images/quan jean den4.jpg',
    '/images/quan jean bac.jpg',
  ],
  'Mũ': [
    '/images/mumautrang.jpg',
    '/images/mudo.jpg',
    '/images/muvang.jpg',
    '/images/muden.jpg',
    '/images/muxanh.jpg',
    '/images/muxanhlacay.jpg',
  ],
};

const productsWithAlternateImages = products.map((product) => {
  if (product.id < 45 || !alternateImages[product.category]) {
    return product;
  }

  const imagePool = alternateImages[product.category];
  return {
    ...product,
    image: imagePool[(product.id - 45) % imagePool.length],
  };
});

export default productsWithAlternateImages;
  