const products = [
  { id: 1, name: 'Mũ Trắng', category: 'Mũ', image: '/images/mumautrang.jpg', price: 1000 },
  { id: 2, name: 'Áo Sơ Mi trắng', category: 'Áo thun', image: '/images/aomitrang.jpg', price: 2000 },
  { id: 3, name: 'Quần Jeans Xanh', category: 'Quần', image: '/images/quanjear1.jpg', price: 5000 },
  { id: 4, name: 'Áo Sơ Mi Đen', category: 'Áo thun', image: '/images/aosomiden2.jpg', price: 500 },
  { id: 5, name: 'Áo Sơ MI Xanh', category: 'Áo thun', image: '/images/aosomixanh.jpg', price: 400 },
  { id: 6, name: 'Mũ Đỏ', category: 'Mũ', image: '/images/mudo.jpg', price: 205 },
  { id: 7, name: 'Áo khoác gió màu đen', category: 'Áo khoác', image: '/images/aokhoac5.jpg', price: 680 },
  { id: 8, name: 'Giày màu tím', category: 'Giày', image: '/images/giaytim.jpg', price: 230 },
  { id: 9, name: 'Quần jean light Blue', category: 'Quần', image: '/images/quan1.jpg', price: 800 },
  { id: 10, name: 'Áo Khoác màu bạc', category: 'Áo khoác', image: '/images/aokhoac20.jpg', price: 330 },
  { id: 11, name: 'Áo khoác trắng', category: 'Áo khoác', image: '/images/aokhoac6.jpg', price: 700 },
  { id: 12, name: 'Áo Sơ mi bạc', category: 'Áo thun', image: '/images/ao somibac.jpg', price: 310 },
  { id: 13, name: 'Mũ Vàng', category: 'Mũ', image: '/images/muvang.jpg', price: 210 },
  { id: 14, name: 'Áo Khoác màu Nâu', category: 'Áo Khoác', image: '/images/aokhoac4.jpg', price: 680 },
  { id: 15, name: 'Áo thun tay ngắn', category: 'Áo thun', image: '/images/shirt.jpg', price: 250 },
  { id: 16, name: 'Giày Xanh', category: 'Giày', image: '/images/giayxanh.jpg', price: 270 },
  { id: 17, name: 'Áo Khoác gió màu đỏ', category: 'Áo khoác', image: '/images/aokhoac13.jpg', price: 430 },
  { id: 18, name: 'Áo thun đen', category: 'Áo thun', image: '/images/aothun4.jpg', price: 230 },
  { id: 19, name: 'Áo Sơ Mi', category: 'Áo thun', image: '/images/aoominagan.jpg', price: 540 },
  { id: 20, name: 'Áo Thun Xanh', category: 'Áo thun', image: '/images/aoxanh.jpg', price: 540 },
  { id: 21, name: 'Áo Khoác da màu nâu', category: 'Áo khoác', image: '/images/aokhoac14.jpg', price: 450 },
  { id: 22, name: 'Áo Khoác đen', category: 'Áo khoác', image: '/images/aokhoac9.jpg', price: 740 },
  { id: 23, name: 'Áo Khoác Gió Red', category: 'Áo khoác', image: '/images/aokhoac2.jpg', price: 500 },
  { id: 24, name: 'Quần Jeans Đen', category: 'Quần', image: '/images/quandn8.jpg', price: 700 },
  { id: 25, name: 'Áo khoác Xanh ', category: 'Áo khoác', image: '/images/aokhoac7.jpg', price: 750 },
  { id: 26, name: 'Áo Khoác G ió black', category: 'Áo khoác', image: '/images/aokhoac1.jpg', price: 500 },
  { id: 27, name: 'Giày trắng', category: 'Giày', image: '/images/giaytrang.jpg', price: 200 },
  { id: 28, name: 'Mũ Đen', category: 'Mũ', image: '/images/muden.jpg', price: 215 },
  { id: 29, name: 'Áo khoác màu đen', category: 'Áo khoác', image: '/images/aokhoac16.jpg', price: 410 },
  { id: 30, name: 'Quần Jeans Bạc', category: 'Quần', image: '/images/quan jean bac.jpg', price: 500 },
  { id: 31, name: 'Mũ Xanh', category: 'Mũ', image: '/images/muxanh.jpg', price: 225 },
  { id: 32, name: 'Giày thể thao', category: 'Giày', image: '/images/giaythethao.jpg', price: 230 },
  { id: 33, name: 'Áo Khoác màu nâu ', category: 'Áo khoác', image: '/images/aokhoac18.jpg', price: 340 },
  { id: 34, name: 'Áo Sơ MI ', category: 'Áo thun', image: '/images/aoomi1.jpg', price: 800 },
  { id: 35, name: 'Quần Jeans Xanh Bạc', category: 'Quần', image: '/images/quan1.jpg', price: 860 },
  { id: 36, name: 'Giày đen', category: 'Giày', image: '/images/giayden.jpg', price: 260 },
  { id: 37, name: 'Áo Thun trắng ', category: 'Áo thun', image: '/images/aothutrang4.jpg', price: 250 },
  { id: 38, name: 'Quần Jeans Đen', category: 'Quần', image: '/images/quan jean den4.jpg', price: 740 },
  { id: 39, name: 'Áo Khoác vàng', category: 'Áo khoác', image: '/images/aokhoac3.jpg', price: 660 },
  { id: 40, name: 'Áo Sơ mi Vàng', category: 'Áo thun', image: '/images/aosomivang.jpg', price: 340 },
  { id: 41, name: 'Giày xanh', category: 'Giày', image: '/images/giay1.jpg', price: 210 },
  { id: 42, name: 'Áo Khoác màu hồng', category: 'Áo khoác', image: '/images/aokhoac11.jpg', price: 380 },
  { id: 43, name: 'Mũ Xanh Lá Cây', category: 'Mũ', image: '/images/muxanhlacay.jpg', price: 208 },
  { id: 44, name: 'Áo khoác nàu nâu', category: 'Áo khoác', image: '/images/aokhoac8.jpg', price: 730 },
  { id: 45, name: 'Giày đen trắng ', category: 'Giày', image: '/images/giaydentrang.jpg', price: 250 }
  ];

  export default products;
  